2025-04-05 18:05:07,474 INFO: Contact Routing System startup [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:26]
2025-04-05 18:05:07,476 INFO: Loading model and data... [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:62]
2025-04-05 18:05:07,476 ERROR: Error loading model and data: [Errno 2] No such file or directory: '../models/routing_model.pkl' [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:83]
2025-04-05 18:06:41,815 INFO: Contact Routing System startup [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:26]
2025-04-05 18:06:41,815 INFO: Loading model and data... [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:62]
2025-04-05 18:06:44,335 ERROR: Error loading model and data: [Errno 2] No such file or directory: '../data/df_clean.pkl' [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:83]
2025-04-05 18:06:54,618 INFO: Contact Routing System startup [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:26]
2025-04-05 18:06:54,619 INFO: Loading model and data... [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:62]
2025-04-05 18:06:55,849 ERROR: Error loading model and data: [Errno 2] No such file or directory: '../data/df_clean.pkl' [in D:\CSU\Bank Clearence Data\db\contact-routing-system\backend\app.py:83]
